### ISSUE TITLE
Remove hardcoded values

### ISSUE THREAD

**Issue by VanyaDNDZ** [LialinMaxim/SSkey#36]
There are some hardcoded values in the code https://github.com/LialinMaxim/SSkey/blob/Development/base.py#L5-L9. Please use env variables and move that values to the docker-compose

**Comment by ArturM94** [comment]
@VanyaDNDZ I can add port and host to docker-compose.yml, also DB user, DB password and DB name to .env file. It's ok or **all** DB settings must contained in .yml file? Because .env file added to .gitignore by default.
And another question. How we will use database environment settings **locally** (without Dockder) for our project if they will be removed from base.py?

**Comment by ArturM94** [comment]
Now the environment variables will be in `.env` for local use:
```
POSTGRES_USER=postgres
POSTGRES_PASS=postgres
POSTGRES_HOST=localhost
POSTGRES_NAME=db_sskey
```

And in `docker-compose.yml` for container use:
```
db:
  image: postgres:10.4
  container_name: sskey_db
  restart: always
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASS=postgres
    - POSTGRES_HOST=172.19.0.2
    - POSTGRES_NAME=db_sskey
```

Import to application:
```
POSTGRES_USER = os.environ.get('POSTGRES_USER')
POSTGRES_PASS = os.environ.get('POSTGRES_PASS')
POSTGRES_HOST = os.environ.get('POSTGRES_HOST')
POSTGRES_NAME = os.environ.get('POSTGRES_DB')
```

It's ok?
